### ISSUE TITLE
format with double underscore

### ISSUE THREAD

**Issue by HoldenJe** [AdamCottrill/glfishr#3]
On thing to note is that the expression for the FN125 attributes have all been updated to use the double underscore convention used internally by Django and many related applications.  So the filters become “tlen__gte” rather than “tlen_gle”.  The double underscore makes it clear that it is an expression or qualifier rather than part of a field name that happens to have an underscore in it.  Currently, the filters in the api have a mix of single and double underscores – **Check and update functions to double underscore throughout**.

**Comment by HoldenJe** [comment]
Update documentation to reflect the change to double underscore.

**Comment by AdamCottrill** [comment]
I believe that all of the single underscores where placed with double underscores in both readme file and function documentation.  Associated with commit: eeea2f897
