### ISSUE TITLE
Hide id and slug columns by default

### ISSUE THREAD

**Issue by rihender** [AdamCottrill/glfishr#4]
Since the values of the id and slug fields change from table to table, if they aren’t fields that will typically be used in analyses, let's hide them by default and add a function to show them. Add a default argument to each of the get_** functions (show_id=FALSE) and then modify the return value accordingly:
`payload <- api_to_dataframe(my_url, recursive = recursive)
if(show_id==FALSE){
    payload <- subset(payload, select=-c(‘id’,’slug’))
}
return(payload)`

**Comment by AdamCottrill** [comment]
This feature has now been merged into main.
