### ISSUE TITLE
Add a function for Flen2Tlen_Lookup

### ISSUE THREAD

**Issue by rihender** [AdamCottrill/glfishr#5]
Add a function to estimate TLEN from FLEN and vice versa. For example:
`get_FN125(list(protocol = “BSM”, lake = “HU”, spc = 334)) %>% mutate(est_tlen = get_est_tlen(flen, spc))`

**Comment by AdamCottrill** [comment]
This is another excellent suggestion. We can incorporate this functionality when we add in the condition factor bounds.  I suspect that will be in the next week or two.

**Comment by AdamCottrill** [comment]
A function (get_flen2tlen()) was added in commit a82f362 and should be available in all releases after 2022.02.24.  This function fetches the coefficients from the api and accepts all of the same filters as the species list. Functions to apply the coefficients to records with missing total length, or inversely missing fork length, as described above still have to be written, but shouldn't be too hard to do.  I am not sure if those function belong in glfishr (which to date has largely focused on getting data from the GLIS API), or another package that could have utilities that do common tasks with data from the api, but don't actually fetch data from it.
