### ISSUE TITLE
Add a warning for filters that don't exist

### ISSUE THREAD

**Issue by rihender** [AdamCottrill/glfishr#7]
If a field is entered into the list of a get_** function that isn’t a filter (e.g. 'gear'), generate a warning or error message. It could say something along the lines of “_Warning: ‘field name’ is not a supported filter. See ‘this website’ or ?function_name for a list of applicable filters._”

**Comment by AdamCottrill** [comment]
I believe that this functionality was implemented in commit daeb0fc.  There are functions to show all of the available filters for an endpoint, and a warning has been integrated into each of the get_FN* functions that will print our any unknown, or mis-specified filters.
